# Copyright 2023 SECO Mind Srl
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
      - 'release-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  reuse:
    uses: ./.github/workflows/reuse-lint.yaml
  rust-codegen:
    needs: [ reuse ]
    uses: ./.github/workflows/rust-codegen.yaml
  rust-check:
    needs: [ rust-codegen ]
    uses: ./.github/workflows/rust-check.yaml
  commit-codegen:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [ rust-check ]
    uses: ./.github/workflows/commit-codegen.yaml
